### ISSUE TITLE
can't read bitbucket_sources_key_copy.dest

### ISSUE THREAD

**Issue by lamhaison** [cognifloyd/ansible-role-bitbucket-sources#1]
Because the first time, the key is not exist then everything ok but in the second time, the task copy don't execute because of existing the key. So the dictionary bitbucket_sources_key_copy doesn't init.

I have create pull request to fix the bug. Hope you can submit the pull request to fix the bug

**Comment by cognifloyd** [comment]
merged. Thanks!
